### ISSUE TITLE
production builds Cannot find module '@/core/utils/labels' 

### ISSUE THREAD

**Issue by hanssl** [kevinjpuscan/react-gauges#1]
I tried this code in a nextjs project.  It works great in development mode.  However, when I try to build the production version of the project (i.e. next build) I get an error.

![Screenshot 2024-03-07 at 12 29 49 PM](https://github.com/kevinjpuscan/react-gauges/assets/649957/7bbd82d3-cb57-41d7-ac4d-6771030d6d28)

**Comment by hanssl** [comment]
This would fix the issues.

--- a/src/components/SimpleGauge/SimpleGauge.tsx
+++ b/src/components/SimpleGauge/SimpleGauge.tsx
@@ -1,6 +1,6 @@
 import React from "react";
 import { GaugeProps } from "./SimpleGauge.types";
-import { getLabel } from "@/core/utils/labels";
+import { getLabel } from "../../core/utils/labels";
 import { useDimensions, useBarParameters } from "./hooks";
 
 export default function SimpleGauge({
diff --git a/src/components/SimpleGauge/hooks/useBarParameters.ts b/src/components/SimpleGauge/hooks/useBarParameters.ts
index 1694f48..d53ece7 100644
--- a/src/components/SimpleGauge/hooks/useBarParameters.ts
+++ b/src/components/SimpleGauge/hooks/useBarParameters.ts
@@ -1,6 +1,6 @@
 import React, { useEffect } from "react";
-import { type SimpleGaugeParameters } from "@/core/simpleGauge/simpleGauge.types";
-import { getSimpleGaugeParameters } from "@/core/simpleGauge";
+import { type SimpleGaugeParameters } from "../../../core/simpleGauge/simpleGauge.types";
+import { getSimpleGaugeParameters } from "../../../core/simpleGauge";
 
 export function useBarParameters(
   width: number,
diff --git a/src/components/SimpleGauge/hooks/useDimensions.ts b/src/components/SimpleGauge/hooks/useDimensions.ts
index 7a3158a..e4c715c 100644
--- a/src/components/SimpleGauge/hooks/useDimensions.ts
+++ b/src/components/SimpleGauge/hooks/useDimensions.ts
@@ -1,5 +1,5 @@
 import React, { useEffect } from "react";
-import { getSimpleGaugeHeightContainer } from "@/core/simpleGauge";
+import { getSimpleGaugeHeightContainer } from "../../../core/simpleGauge";
 
 export function useDimensions(gaugeContainer: React.RefObject<HTMLDivElement>, barWidth: number, isTotal: boolean) {
   const getContainerWidth = (gaugeContainer: React.RefObject<HTMLDivElement>) => {
@@ -14,9 +14,9 @@ export function useDimensions(gaugeContainer: React.RefObject<HTMLDivElement>, b
     const height = isTotal
       ? width
       : getSimpleGaugeHeightContainer({
-          width: width,
-          strokeWidth: barWidth,
-        });
+        width: width,
+        strokeWidth: barWidth,
+      });
     return { width, height };
   };

**Comment by kevinjpuscan** [comment]
Hello, I just removed the path aliases from the project to avoid any problems. Thank you very much for raising the problem.
